Update sc tools to use v0.0.34 docker image
datirium/workflows pull request #194
Opened 2024-03-12 03:03 UTC by michael-kotliar

- Use intrinsicDimension to estimate dimensionality
    in sc_rna_reduce.R and sc_rna_cluster.R scripts
    if --dimensions parameter was set to 0
  - Allow to show density levels on UMAP (see
    dim_plot function from graphics.R)
  - Show cell counts on the composition plots (can
    disabled when label parameter is set to FALSE)
  - Allow to set seed in all scripts
  - Automatically estimate --minumis, --mingenes,
    --maxgenes, --maxmt, and --minfragments filtering
    thresholds if set to 0 (related to sc_rna_filter.R
    and sc_multiome_filter.R scripts)
  - Updated plots for cell counts comparison between
    datasets, groups, clusters, etc in
    sc_[rna/atac/wnn]_cluster.R and sc_ctype_assign.R
    scripts
  - Add optional --reduction to sc_ctype_assign.R
    scripts to outputs plots only to selected reduction
    (if not provided, it will be defined based on the
    --source parameter)
  - Added "RNA reads vs mitochondrial % per cell" plot in
    sc_rna_filter.R and sc_multiome_filter.R scripts
  - Set the default normalization method in sc_rna_reduce.R
    to sctglm

2024-03-20 17:11 UTC, scrowley-Datirium requested changes

2024-03-20 17:11 UTC, scrowley-Datirium commented on workflows/cellranger-mkref.cwl
> +  - "https://github.com/datirium/workflows/workflows/genome-indices.cwl"
remove url upstream

2024-03-20 17:11 UTC, scrowley-Datirium commented on workflows/cellranger-multi.cwl
> +    default: "6"
6 core default may be too much, even for clusters (10 SC samples running at once would be 60 threads)

2024-03-22 19:33 UTC, michael-kotliar commented on workflows/cellranger-multi.cwl
> +    default: "6"
For cluster it might still ok, as we are limited to 100 CPUs, however, when we have some steps run in parallel, we could go even above 60. I set all threads to 4 by default.

2024-03-25 17:01 UTC, scrowley-Datirium approved these changes
LGTM

2024-03-25 17:49 UTC, merged